repos:
#####
# Basic file cleanliness
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace

# R
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9030
    hooks:
    -   id: use-tidy-description
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-print-statement
    -   id: no-debug-statement
    -   id: deps-in-desc
        exclude: data-raw

-   repo: https://github.com/posit-dev/air-pre-commit
    rev: 0.11.0
    hooks:
      - id: air-format
-   repo: https://github.com/etiennebacher/jarl-pre-commit
    rev: 0.5.0
    hooks:
      - id: jarl-check
        args: ["--fix", "--allow-dirty"]
#####
# Secrets
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
