# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  build:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      id-token: write
      pages: write
    outputs:
      page_artifact_id: ${{ steps.upload-artifact.outputs.artifact_id }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.19.2"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          use-public-rspm: true
          install-r: false
          extra-repositories: "https://mc-stan.org/r-packages/"
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: rc
          extra-packages: any::pkgdown local::.
          needs: website

      - name: "Install cmdstan via cmdstanr"
        uses: epinowcast/actions/install-cmdstan@v1
        with:
          cmdstan-version: "latest"

      - name: Build site
        run: "pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)"
        shell: Rscript {0}

      - name: Upload artifact for GH pages deployment
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/"

  deploy:
    # check builds on PRs but only deploy when main changes
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4

  post-page-artifact:
    needs: build
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
           issue-number: ${{ github.event.pull_request.number }}
           comment-author: 'github-actions[bot]'
           body-includes: Your page is ready to preview

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for your contribution, @${{ github.triggering_actor }} :rocket:! Your page is ready to preview [here](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}/artifacts/${{ needs.build.outputs.page_artifact_id }})
          edit-mode: replace
