name: R CMD check project packages

on:
  pull_request:
  push:
    branches: [main, prod]

jobs:
  check-package:
    strategy:
      matrix:
        r-version: ["4.1.0", "release"]
        os: [windows-latest, ubuntu-latest]
    runs-on:  ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r-version}}
        use-public-rspm: true
        extra-repositories: "https://mc-stan.org/r-packages/"
    - name: "Set up dependencies for wwinference"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        needs: check
    - name: "Install cmdstan via cmdstanr"
      if: runner.os != 'windows-latest'
      uses: epinowcast/actions/install-cmdstan@v1
      with:
        cmdstan-version: "latest"

    - name: "Setting conda"
      if: runner.os == 'windows-latest'
      uses: conda-incubator/setup-miniconda@3.0.4
      with:
        activate-environment: 'stan'

    - name: "Installing cmdstan via conda"
      if: runner.os == 'windows-latest'
      run: |
        conda install -c conda-forge cmdstan
        conda activate stan

    - name: "Check wwinference package"
      uses: r-lib/actions/check-r-package@v2
      with:
        build_args: 'c("--no-manual", "--no-build-vignettes")'
        args: 'c("--no-manual", "--as-cran", "--ignore-vignettes")'
