name: R CMD check project packages

on:
  pull_request:
  push:
    branches: [main, prod]

jobs:
  check-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.1.0"
        use-public-rspm: true
        extra-repositories: "https://mc-stan.org/r-packages/"
    - name: "Set up dependencies for wwinference"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        needs: check
    - name: "Install cmdstan via cmdstanr"
      uses: epinowcast/actions/install-cmdstan@v1
      with:
        cmdstan-version: "latest"
    - name: "Check wwinference package"
      uses: r-lib/actions/check-r-package@v2
      with:
        build_args: 'c("--no-manual", "--no-build-vignettes")'
        args: 'c("--no-manual", "--as-cran", "--ignore-vignettes")'
